apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
  namespace: demo
spec:
  containers:
  - name: app
    image: busybox
    securityContext:
      privileged: true
    command: ["sleep", "3600"]
